### PR TITLE
Add 'getFieldOr' helper

### LINKED ISSUE #10: Add getFieldOr
It's a common idiom to do something like `fromMaybe def <$> getField "field"`; let's just add this common case. No need to add `getFieldOrWith`/`getFieldsOr`/`getFieldsOrWith` variants.

### PR DESCRIPTION
**Pull request by rvarago**
Hi,

Thanks for this nice library!

I took the liberty of putting a small patch together. Let me know your thoughts.

---

This small helper is meant to handle the case where there's
a sensible default value for a potentially missing key.

Resolves #10

### CODE REVIEW

**Review by brandonchinn178 — APPROVED** [review]
Looks great! Thank you!

**Comment by brandonchinn178** [comment]
@rvarago can you fix formatting per ci?

**Comment by brandonchinn178** [comment]
Can you also update the changelog?

**Comment by rvarago** [comment]
@brandonchinn178 

Oops. I forgot to run `fourmolu` _just_ before pushing the patch :see_no_evil:, sorry!

Sure. It's done, both.

**Comment by brandonchinn178** [comment]
Can you change the markdown bullet point back? I don't want to introduce a bad merge conflict for the other PR

**Comment by rvarago** [comment]
> Can you change the markdown bullet point back? I don't want to introduce a bad merge conflict for the other PR

Absolutely. It shouldn't be there in the first place, my editor might've re-written it and I didn't pre-review the patch properly before pushing it.

Done.

**Comment by brandonchinn178** [comment]
Thanks a ton!

**Pull request merged**
